// @exclude
//
// Copyright © contributors to CloudNativePG, established as
// CloudNativePG a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/logs.proto

package logs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogsCapability_RPC_Type int32

const (
	LogsCapability_RPC_TYPE_UNSPECIFIED LogsCapability_RPC_Type = 0
	// TYPE_SERVER_LOGS indicates that the Plugin is able to respond
	// to UploadServerLogs RPC streaming requests.
	LogsCapability_RPC_TYPE_SERVER_LOGS LogsCapability_RPC_Type = 1
	// TYPE_AUDIT_LOGS indicates that the Plugin is able to respond
	// to UploadAuditLogs RPC streaming requests.
	LogsCapability_RPC_TYPE_AUDIT_LOGS LogsCapability_RPC_Type = 2
)

// Enum value maps for LogsCapability_RPC_Type.
var (
	LogsCapability_RPC_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_SERVER_LOGS",
		2: "TYPE_AUDIT_LOGS",
	}
	LogsCapability_RPC_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_SERVER_LOGS": 1,
		"TYPE_AUDIT_LOGS":  2,
	}
)

func (x LogsCapability_RPC_Type) Enum() *LogsCapability_RPC_Type {
	p := new(LogsCapability_RPC_Type)
	*p = x
	return p
}

func (x LogsCapability_RPC_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogsCapability_RPC_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logs_proto_enumTypes[0].Descriptor()
}

func (LogsCapability_RPC_Type) Type() protoreflect.EnumType {
	return &file_proto_logs_proto_enumTypes[0]
}

func (x LogsCapability_RPC_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogsCapability_RPC_Type.Descriptor instead.
func (LogsCapability_RPC_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{2, 0, 0}
}

type LogsCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsCapabilitiesRequest) Reset() {
	*x = LogsCapabilitiesRequest{}
	mi := &file_proto_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsCapabilitiesRequest) ProtoMessage() {}

func (x *LogsCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*LogsCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{0}
}

type LogsCapabilitiesResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All the capabilities the plugin supports.  This field is OPTIONAL.
	Capabilities  []*LogsCapability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsCapabilitiesResult) Reset() {
	*x = LogsCapabilitiesResult{}
	mi := &file_proto_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsCapabilitiesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsCapabilitiesResult) ProtoMessage() {}

func (x *LogsCapabilitiesResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsCapabilitiesResult.ProtoReflect.Descriptor instead.
func (*LogsCapabilitiesResult) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{1}
}

func (x *LogsCapabilitiesResult) GetCapabilities() []*LogsCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type LogsCapability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*LogsCapability_Rpc
	Type          isLogsCapability_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsCapability) Reset() {
	*x = LogsCapability{}
	mi := &file_proto_logs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsCapability) ProtoMessage() {}

func (x *LogsCapability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsCapability.ProtoReflect.Descriptor instead.
func (*LogsCapability) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{2}
}

func (x *LogsCapability) GetType() isLogsCapability_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *LogsCapability) GetRpc() *LogsCapability_RPC {
	if x != nil {
		if x, ok := x.Type.(*LogsCapability_Rpc); ok {
			return x.Rpc
		}
	}
	return nil
}

type isLogsCapability_Type interface {
	isLogsCapability_Type()
}

type LogsCapability_Rpc struct {
	Rpc *LogsCapability_RPC `protobuf:"bytes,1,opt,name=rpc,proto3,oneof"`
}

func (*LogsCapability_Rpc) isLogsCapability_Type() {}

type UploadServerLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The field is REQUIRED and contains the Postgres log entries emitted
	// into the CSV logging collector.  The server may choose to send one
	// request per entry or to batch multiple log entries into a single
	// request.
	Entries       []*UploadServerLogsRequest_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadServerLogsRequest) Reset() {
	*x = UploadServerLogsRequest{}
	mi := &file_proto_logs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadServerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadServerLogsRequest) ProtoMessage() {}

func (x *UploadServerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadServerLogsRequest.ProtoReflect.Descriptor instead.
func (*UploadServerLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{3}
}

func (x *UploadServerLogsRequest) GetEntries() []*UploadServerLogsRequest_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type UploadServerLogsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadServerLogsResult) Reset() {
	*x = UploadServerLogsResult{}
	mi := &file_proto_logs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadServerLogsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadServerLogsResult) ProtoMessage() {}

func (x *UploadServerLogsResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadServerLogsResult.ProtoReflect.Descriptor instead.
func (*UploadServerLogsResult) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{4}
}

type UploadAuditLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The field is REQUIRED and contains the PgAudit log entries emitted
	// into the CSV logging collector.  The server may choose to send one
	// request per entry or to batch multiple log entries into a single
	// request.
	Entries       []*UploadAuditLogsRequest_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAuditLogsRequest) Reset() {
	*x = UploadAuditLogsRequest{}
	mi := &file_proto_logs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAuditLogsRequest) ProtoMessage() {}

func (x *UploadAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*UploadAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{5}
}

func (x *UploadAuditLogsRequest) GetEntries() []*UploadAuditLogsRequest_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type UploadAuditLogsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAuditLogsResult) Reset() {
	*x = UploadAuditLogsResult{}
	mi := &file_proto_logs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAuditLogsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAuditLogsResult) ProtoMessage() {}

func (x *UploadAuditLogsResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAuditLogsResult.ProtoReflect.Descriptor instead.
func (*UploadAuditLogsResult) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{6}
}

type LogsCapability_RPC struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          LogsCapability_RPC_Type `protobuf:"varint,1,opt,name=type,proto3,enum=cnpgi.logs.v1.LogsCapability_RPC_Type" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsCapability_RPC) Reset() {
	*x = LogsCapability_RPC{}
	mi := &file_proto_logs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsCapability_RPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsCapability_RPC) ProtoMessage() {}

func (x *LogsCapability_RPC) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsCapability_RPC.ProtoReflect.Descriptor instead.
func (*LogsCapability_RPC) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{2, 0}
}

func (x *LogsCapability_RPC) GetType() LogsCapability_RPC_Type {
	if x != nil {
		return x.Type
	}
	return LogsCapability_RPC_TYPE_UNSPECIFIED
}

type UploadServerLogsRequest_Entry struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LogTime              string                 `protobuf:"bytes,1,opt,name=log_time,json=logTime,proto3" json:"log_time,omitempty"`
	UserName             string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	DatabaseName         string                 `protobuf:"bytes,3,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	ProcessId            string                 `protobuf:"bytes,4,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ConnectionFrom       string                 `protobuf:"bytes,5,opt,name=connection_from,json=connectionFrom,proto3" json:"connection_from,omitempty"`
	SessionId            string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionLineNum       string                 `protobuf:"bytes,7,opt,name=session_line_num,json=sessionLineNum,proto3" json:"session_line_num,omitempty"`
	CommandTag           string                 `protobuf:"bytes,8,opt,name=command_tag,json=commandTag,proto3" json:"command_tag,omitempty"`
	SessionStartTime     string                 `protobuf:"bytes,9,opt,name=session_start_time,json=sessionStartTime,proto3" json:"session_start_time,omitempty"`
	VirtualTransactionId string                 `protobuf:"bytes,10,opt,name=virtual_transaction_id,json=virtualTransactionId,proto3" json:"virtual_transaction_id,omitempty"`
	TransactionId        string                 `protobuf:"bytes,11,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ErrorSeverity        string                 `protobuf:"bytes,12,opt,name=error_severity,json=errorSeverity,proto3" json:"error_severity,omitempty"`
	SqlStateCode         string                 `protobuf:"bytes,13,opt,name=sql_state_code,json=sqlStateCode,proto3" json:"sql_state_code,omitempty"`
	Message              string                 `protobuf:"bytes,14,opt,name=message,proto3" json:"message,omitempty"`
	Detail               string                 `protobuf:"bytes,15,opt,name=detail,proto3" json:"detail,omitempty"`
	Hint                 string                 `protobuf:"bytes,16,opt,name=hint,proto3" json:"hint,omitempty"`
	InternalQuery        string                 `protobuf:"bytes,17,opt,name=internal_query,json=internalQuery,proto3" json:"internal_query,omitempty"`
	InternalQueryPos     string                 `protobuf:"bytes,18,opt,name=internal_query_pos,json=internalQueryPos,proto3" json:"internal_query_pos,omitempty"`
	Context              string                 `protobuf:"bytes,19,opt,name=context,proto3" json:"context,omitempty"`
	Query                string                 `protobuf:"bytes,20,opt,name=query,proto3" json:"query,omitempty"`
	QueryPos             string                 `protobuf:"bytes,21,opt,name=query_pos,json=queryPos,proto3" json:"query_pos,omitempty"`
	Location             string                 `protobuf:"bytes,22,opt,name=location,proto3" json:"location,omitempty"`
	ApplicationName      string                 `protobuf:"bytes,23,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	BackendType          string                 `protobuf:"bytes,24,opt,name=backend_type,json=backendType,proto3" json:"backend_type,omitempty"`
	LeaderPid            string                 `protobuf:"bytes,25,opt,name=leader_pid,json=leaderPid,proto3" json:"leader_pid,omitempty"`
	QueryId              string                 `protobuf:"bytes,26,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UploadServerLogsRequest_Entry) Reset() {
	*x = UploadServerLogsRequest_Entry{}
	mi := &file_proto_logs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadServerLogsRequest_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadServerLogsRequest_Entry) ProtoMessage() {}

func (x *UploadServerLogsRequest_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadServerLogsRequest_Entry.ProtoReflect.Descriptor instead.
func (*UploadServerLogsRequest_Entry) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UploadServerLogsRequest_Entry) GetLogTime() string {
	if x != nil {
		return x.LogTime
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetConnectionFrom() string {
	if x != nil {
		return x.ConnectionFrom
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetSessionLineNum() string {
	if x != nil {
		return x.SessionLineNum
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetCommandTag() string {
	if x != nil {
		return x.CommandTag
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetSessionStartTime() string {
	if x != nil {
		return x.SessionStartTime
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetVirtualTransactionId() string {
	if x != nil {
		return x.VirtualTransactionId
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetErrorSeverity() string {
	if x != nil {
		return x.ErrorSeverity
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetSqlStateCode() string {
	if x != nil {
		return x.SqlStateCode
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetInternalQuery() string {
	if x != nil {
		return x.InternalQuery
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetInternalQueryPos() string {
	if x != nil {
		return x.InternalQueryPos
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetQueryPos() string {
	if x != nil {
		return x.QueryPos
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetBackendType() string {
	if x != nil {
		return x.BackendType
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetLeaderPid() string {
	if x != nil {
		return x.LeaderPid
	}
	return ""
}

func (x *UploadServerLogsRequest_Entry) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

type UploadAuditLogsRequest_Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of SESSION or OBJECT.
	AuditType string `protobuf:"bytes,1,opt,name=audit_type,json=auditType,proto3" json:"audit_type,omitempty"`
	// Unique statement ID for this session. Each statement ID
	// represents a backend call. Statement IDs are sequential even if
	// some statements are not logged. There may be multiple entries for
	// a statement ID when more than one relation is logged.
	StatementId string `protobuf:"bytes,2,opt,name=statement_id,json=statementId,proto3" json:"statement_id,omitempty"`
	// Sequential ID for each sub-statement within the main statement.
	// For example, calling a function from a query. Sub-statement IDs
	// are continuous even if some sub-statements are not logged. There
	// may be multiple entries for a sub-statement ID when more than one
	// relation is logged.
	SubstatementId string `protobuf:"bytes,3,opt,name=substatement_id,json=substatementId,proto3" json:"substatement_id,omitempty"`
	// One of READ, WRITE, FUNCTION, ROLE, DDL, MISC, MISC_SET.
	Class string `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	// One of ALTER TABLE, SELECT, etc (command tags).
	Command string `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	// One of TABLE, INDEX, VIEW, etc. Available for SELECT, DML and
	// most DDL statements.
	ObjectType string `protobuf:"bytes,6,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// The fully-qualified object name (e.g. public.account). Available
	// for SELECT, DML and most DDL statements.
	ObjectName string `protobuf:"bytes,7,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	// SQL statement executed on the backend.
	Statement string `protobuf:"bytes,8,opt,name=statement,proto3" json:"statement,omitempty"`
	// If pgaudit.log_parameter is set then this field will contain the
	// statement parameters as quoted CSV or <none> if there are no
	// parameters. Otherwise, the field is <not logged>.
	Parameter     string `protobuf:"bytes,9,opt,name=parameter,proto3" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAuditLogsRequest_Entry) Reset() {
	*x = UploadAuditLogsRequest_Entry{}
	mi := &file_proto_logs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAuditLogsRequest_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAuditLogsRequest_Entry) ProtoMessage() {}

func (x *UploadAuditLogsRequest_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAuditLogsRequest_Entry.ProtoReflect.Descriptor instead.
func (*UploadAuditLogsRequest_Entry) Descriptor() ([]byte, []int) {
	return file_proto_logs_proto_rawDescGZIP(), []int{5, 0}
}

func (x *UploadAuditLogsRequest_Entry) GetAuditType() string {
	if x != nil {
		return x.AuditType
	}
	return ""
}

func (x *UploadAuditLogsRequest_Entry) GetStatementId() string {
	if x != nil {
		return x.StatementId
	}
	return ""
}

func (x *UploadAuditLogsRequest_Entry) GetSubstatementId() string {
	if x != nil {
		return x.SubstatementId
	}
	return ""
}

func (x *UploadAuditLogsRequest_Entry) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *UploadAuditLogsRequest_Entry) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *UploadAuditLogsRequest_Entry) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *UploadAuditLogsRequest_Entry) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *UploadAuditLogsRequest_Entry) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *UploadAuditLogsRequest_Entry) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

var File_proto_logs_proto protoreflect.FileDescriptor

const file_proto_logs_proto_rawDesc = "" +
	"\n" +
	"\x10proto/logs.proto\x12\rcnpgi.logs.v1\"\x19\n" +
	"\x17LogsCapabilitiesRequest\"[\n" +
	"\x16LogsCapabilitiesResult\x12A\n" +
	"\fcapabilities\x18\x01 \x03(\v2\x1d.cnpgi.logs.v1.LogsCapabilityR\fcapabilities\"\xdc\x01\n" +
	"\x0eLogsCapability\x125\n" +
	"\x03rpc\x18\x01 \x01(\v2!.cnpgi.logs.v1.LogsCapability.RPCH\x00R\x03rpc\x1a\x8a\x01\n" +
	"\x03RPC\x12:\n" +
	"\x04type\x18\x01 \x01(\x0e2&.cnpgi.logs.v1.LogsCapability.RPC.TypeR\x04type\"G\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TYPE_SERVER_LOGS\x10\x01\x12\x13\n" +
	"\x0fTYPE_AUDIT_LOGS\x10\x02B\x06\n" +
	"\x04type\"\xde\a\n" +
	"\x17UploadServerLogsRequest\x12F\n" +
	"\aentries\x18\x01 \x03(\v2,.cnpgi.logs.v1.UploadServerLogsRequest.EntryR\aentries\x1a\xfa\x06\n" +
	"\x05Entry\x12\x19\n" +
	"\blog_time\x18\x01 \x01(\tR\alogTime\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12#\n" +
	"\rdatabase_name\x18\x03 \x01(\tR\fdatabaseName\x12\x1d\n" +
	"\n" +
	"process_id\x18\x04 \x01(\tR\tprocessId\x12'\n" +
	"\x0fconnection_from\x18\x05 \x01(\tR\x0econnectionFrom\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12(\n" +
	"\x10session_line_num\x18\a \x01(\tR\x0esessionLineNum\x12\x1f\n" +
	"\vcommand_tag\x18\b \x01(\tR\n" +
	"commandTag\x12,\n" +
	"\x12session_start_time\x18\t \x01(\tR\x10sessionStartTime\x124\n" +
	"\x16virtual_transaction_id\x18\n" +
	" \x01(\tR\x14virtualTransactionId\x12%\n" +
	"\x0etransaction_id\x18\v \x01(\tR\rtransactionId\x12%\n" +
	"\x0eerror_severity\x18\f \x01(\tR\rerrorSeverity\x12$\n" +
	"\x0esql_state_code\x18\r \x01(\tR\fsqlStateCode\x12\x18\n" +
	"\amessage\x18\x0e \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x0f \x01(\tR\x06detail\x12\x12\n" +
	"\x04hint\x18\x10 \x01(\tR\x04hint\x12%\n" +
	"\x0einternal_query\x18\x11 \x01(\tR\rinternalQuery\x12,\n" +
	"\x12internal_query_pos\x18\x12 \x01(\tR\x10internalQueryPos\x12\x18\n" +
	"\acontext\x18\x13 \x01(\tR\acontext\x12\x14\n" +
	"\x05query\x18\x14 \x01(\tR\x05query\x12\x1b\n" +
	"\tquery_pos\x18\x15 \x01(\tR\bqueryPos\x12\x1a\n" +
	"\blocation\x18\x16 \x01(\tR\blocation\x12)\n" +
	"\x10application_name\x18\x17 \x01(\tR\x0fapplicationName\x12!\n" +
	"\fbackend_type\x18\x18 \x01(\tR\vbackendType\x12\x1d\n" +
	"\n" +
	"leader_pid\x18\x19 \x01(\tR\tleaderPid\x12\x19\n" +
	"\bquery_id\x18\x1a \x01(\tR\aqueryId\"\x18\n" +
	"\x16UploadServerLogsResult\"\x82\x03\n" +
	"\x16UploadAuditLogsRequest\x12E\n" +
	"\aentries\x18\x01 \x03(\v2+.cnpgi.logs.v1.UploadAuditLogsRequest.EntryR\aentries\x1a\xa0\x02\n" +
	"\x05Entry\x12\x1d\n" +
	"\n" +
	"audit_type\x18\x01 \x01(\tR\tauditType\x12!\n" +
	"\fstatement_id\x18\x02 \x01(\tR\vstatementId\x12'\n" +
	"\x0fsubstatement_id\x18\x03 \x01(\tR\x0esubstatementId\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x1f\n" +
	"\vobject_type\x18\x06 \x01(\tR\n" +
	"objectType\x12\x1f\n" +
	"\vobject_name\x18\a \x01(\tR\n" +
	"objectName\x12\x1c\n" +
	"\tstatement\x18\b \x01(\tR\tstatement\x12\x1c\n" +
	"\tparameter\x18\t \x01(\tR\tparameter\"\x17\n" +
	"\x15UploadAuditLogsResult2\xaf\x02\n" +
	"\x04Logs\x12`\n" +
	"\x0fGetCapabilities\x12&.cnpgi.logs.v1.LogsCapabilitiesRequest\x1a%.cnpgi.logs.v1.LogsCapabilitiesResult\x12c\n" +
	"\x10UploadServerLogs\x12&.cnpgi.logs.v1.UploadServerLogsRequest\x1a%.cnpgi.logs.v1.UploadServerLogsResult(\x01\x12`\n" +
	"\x0fUploadAuditLogs\x12%.cnpgi.logs.v1.UploadAuditLogsRequest\x1a$.cnpgi.logs.v1.UploadAuditLogsResult(\x01B+Z)github.com/cloudnative-pg/cnpg-i/pkg/logsb\x06proto3"

var (
	file_proto_logs_proto_rawDescOnce sync.Once
	file_proto_logs_proto_rawDescData []byte
)

func file_proto_logs_proto_rawDescGZIP() []byte {
	file_proto_logs_proto_rawDescOnce.Do(func() {
		file_proto_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logs_proto_rawDesc), len(file_proto_logs_proto_rawDesc)))
	})
	return file_proto_logs_proto_rawDescData
}

var file_proto_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_logs_proto_goTypes = []any{
	(LogsCapability_RPC_Type)(0),          // 0: cnpgi.logs.v1.LogsCapability.RPC.Type
	(*LogsCapabilitiesRequest)(nil),       // 1: cnpgi.logs.v1.LogsCapabilitiesRequest
	(*LogsCapabilitiesResult)(nil),        // 2: cnpgi.logs.v1.LogsCapabilitiesResult
	(*LogsCapability)(nil),                // 3: cnpgi.logs.v1.LogsCapability
	(*UploadServerLogsRequest)(nil),       // 4: cnpgi.logs.v1.UploadServerLogsRequest
	(*UploadServerLogsResult)(nil),        // 5: cnpgi.logs.v1.UploadServerLogsResult
	(*UploadAuditLogsRequest)(nil),        // 6: cnpgi.logs.v1.UploadAuditLogsRequest
	(*UploadAuditLogsResult)(nil),         // 7: cnpgi.logs.v1.UploadAuditLogsResult
	(*LogsCapability_RPC)(nil),            // 8: cnpgi.logs.v1.LogsCapability.RPC
	(*UploadServerLogsRequest_Entry)(nil), // 9: cnpgi.logs.v1.UploadServerLogsRequest.Entry
	(*UploadAuditLogsRequest_Entry)(nil),  // 10: cnpgi.logs.v1.UploadAuditLogsRequest.Entry
}
var file_proto_logs_proto_depIdxs = []int32{
	3,  // 0: cnpgi.logs.v1.LogsCapabilitiesResult.capabilities:type_name -> cnpgi.logs.v1.LogsCapability
	8,  // 1: cnpgi.logs.v1.LogsCapability.rpc:type_name -> cnpgi.logs.v1.LogsCapability.RPC
	9,  // 2: cnpgi.logs.v1.UploadServerLogsRequest.entries:type_name -> cnpgi.logs.v1.UploadServerLogsRequest.Entry
	10, // 3: cnpgi.logs.v1.UploadAuditLogsRequest.entries:type_name -> cnpgi.logs.v1.UploadAuditLogsRequest.Entry
	0,  // 4: cnpgi.logs.v1.LogsCapability.RPC.type:type_name -> cnpgi.logs.v1.LogsCapability.RPC.Type
	1,  // 5: cnpgi.logs.v1.Logs.GetCapabilities:input_type -> cnpgi.logs.v1.LogsCapabilitiesRequest
	4,  // 6: cnpgi.logs.v1.Logs.UploadServerLogs:input_type -> cnpgi.logs.v1.UploadServerLogsRequest
	6,  // 7: cnpgi.logs.v1.Logs.UploadAuditLogs:input_type -> cnpgi.logs.v1.UploadAuditLogsRequest
	2,  // 8: cnpgi.logs.v1.Logs.GetCapabilities:output_type -> cnpgi.logs.v1.LogsCapabilitiesResult
	5,  // 9: cnpgi.logs.v1.Logs.UploadServerLogs:output_type -> cnpgi.logs.v1.UploadServerLogsResult
	7,  // 10: cnpgi.logs.v1.Logs.UploadAuditLogs:output_type -> cnpgi.logs.v1.UploadAuditLogsResult
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_logs_proto_init() }
func file_proto_logs_proto_init() {
	if File_proto_logs_proto != nil {
		return
	}
	file_proto_logs_proto_msgTypes[2].OneofWrappers = []any{
		(*LogsCapability_Rpc)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logs_proto_rawDesc), len(file_proto_logs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logs_proto_goTypes,
		DependencyIndexes: file_proto_logs_proto_depIdxs,
		EnumInfos:         file_proto_logs_proto_enumTypes,
		MessageInfos:      file_proto_logs_proto_msgTypes,
	}.Build()
	File_proto_logs_proto = out.File
	file_proto_logs_proto_goTypes = nil
	file_proto_logs_proto_depIdxs = nil
}
