// @exclude
//
// Copyright © contributors to CloudNativePG, established as
// CloudNativePG a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/logs.proto

package logs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Logs_GetCapabilities_FullMethodName  = "/cnpgi.logs.v1.Logs/GetCapabilities"
	Logs_UploadServerLogs_FullMethodName = "/cnpgi.logs.v1.Logs/UploadServerLogs"
	Logs_UploadAuditLogs_FullMethodName  = "/cnpgi.logs.v1.Logs/UploadAuditLogs"
)

// LogsClient is the client API for Logs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogsClient interface {
	// GetCapabilities gets the capabilities of the Logs service.
	GetCapabilities(ctx context.Context, in *LogsCapabilitiesRequest, opts ...grpc.CallOption) (*LogsCapabilitiesResult, error)
	// UploadServerLogs streams Postgres log entries to service.
	UploadServerLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadServerLogsRequest, UploadServerLogsResult], error)
	// UploadAuditLogs streams PgAudit log entries to service.
	UploadAuditLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadAuditLogsRequest, UploadAuditLogsResult], error)
}

type logsClient struct {
	cc grpc.ClientConnInterface
}

func NewLogsClient(cc grpc.ClientConnInterface) LogsClient {
	return &logsClient{cc}
}

func (c *logsClient) GetCapabilities(ctx context.Context, in *LogsCapabilitiesRequest, opts ...grpc.CallOption) (*LogsCapabilitiesResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogsCapabilitiesResult)
	err := c.cc.Invoke(ctx, Logs_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logsClient) UploadServerLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadServerLogsRequest, UploadServerLogsResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Logs_ServiceDesc.Streams[0], Logs_UploadServerLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadServerLogsRequest, UploadServerLogsResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Logs_UploadServerLogsClient = grpc.ClientStreamingClient[UploadServerLogsRequest, UploadServerLogsResult]

func (c *logsClient) UploadAuditLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadAuditLogsRequest, UploadAuditLogsResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Logs_ServiceDesc.Streams[1], Logs_UploadAuditLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadAuditLogsRequest, UploadAuditLogsResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Logs_UploadAuditLogsClient = grpc.ClientStreamingClient[UploadAuditLogsRequest, UploadAuditLogsResult]

// LogsServer is the server API for Logs service.
// All implementations must embed UnimplementedLogsServer
// for forward compatibility.
type LogsServer interface {
	// GetCapabilities gets the capabilities of the Logs service.
	GetCapabilities(context.Context, *LogsCapabilitiesRequest) (*LogsCapabilitiesResult, error)
	// UploadServerLogs streams Postgres log entries to service.
	UploadServerLogs(grpc.ClientStreamingServer[UploadServerLogsRequest, UploadServerLogsResult]) error
	// UploadAuditLogs streams PgAudit log entries to service.
	UploadAuditLogs(grpc.ClientStreamingServer[UploadAuditLogsRequest, UploadAuditLogsResult]) error
	mustEmbedUnimplementedLogsServer()
}

// UnimplementedLogsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogsServer struct{}

func (UnimplementedLogsServer) GetCapabilities(context.Context, *LogsCapabilitiesRequest) (*LogsCapabilitiesResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedLogsServer) UploadServerLogs(grpc.ClientStreamingServer[UploadServerLogsRequest, UploadServerLogsResult]) error {
	return status.Error(codes.Unimplemented, "method UploadServerLogs not implemented")
}
func (UnimplementedLogsServer) UploadAuditLogs(grpc.ClientStreamingServer[UploadAuditLogsRequest, UploadAuditLogsResult]) error {
	return status.Error(codes.Unimplemented, "method UploadAuditLogs not implemented")
}
func (UnimplementedLogsServer) mustEmbedUnimplementedLogsServer() {}
func (UnimplementedLogsServer) testEmbeddedByValue()              {}

// UnsafeLogsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogsServer will
// result in compilation errors.
type UnsafeLogsServer interface {
	mustEmbedUnimplementedLogsServer()
}

func RegisterLogsServer(s grpc.ServiceRegistrar, srv LogsServer) {
	// If the following call panics, it indicates UnimplementedLogsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Logs_ServiceDesc, srv)
}

func _Logs_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Logs_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsServer).GetCapabilities(ctx, req.(*LogsCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logs_UploadServerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogsServer).UploadServerLogs(&grpc.GenericServerStream[UploadServerLogsRequest, UploadServerLogsResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Logs_UploadServerLogsServer = grpc.ClientStreamingServer[UploadServerLogsRequest, UploadServerLogsResult]

func _Logs_UploadAuditLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogsServer).UploadAuditLogs(&grpc.GenericServerStream[UploadAuditLogsRequest, UploadAuditLogsResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Logs_UploadAuditLogsServer = grpc.ClientStreamingServer[UploadAuditLogsRequest, UploadAuditLogsResult]

// Logs_ServiceDesc is the grpc.ServiceDesc for Logs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Logs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cnpgi.logs.v1.Logs",
	HandlerType: (*LogsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _Logs_GetCapabilities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadServerLogs",
			Handler:       _Logs_UploadServerLogs_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UploadAuditLogs",
			Handler:       _Logs_UploadAuditLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/logs.proto",
}
